// <auto-generated />
using System;
using Farmacia_Paolo.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Farmacia_Papolo.Migrations
{
    [DbContext(typeof(FarmaciaContext))]
    [Migration("20251103004059_MigracionInicialConSeedData")]
    partial class MigracionInicialConSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("Farmacia_Paolo.Models.Lote", b =>
                {
                    b.Property<int>("LoteID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CantidadActual")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaEntrada")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaVencimiento")
                        .HasColumnType("TEXT");

                    b.Property<string>("NumeroLote")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductoID")
                        .HasColumnType("INTEGER");

                    b.HasKey("LoteID");

                    b.HasIndex("ProductoID");

                    b.ToTable("Lotes");

                    b.HasData(
                        new
                        {
                            LoteID = 1,
                            CantidadActual = 100,
                            FechaEntrada = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaVencimiento = new DateTime(2026, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NumeroLote = "LOTE-A100",
                            ProductoID = 1
                        },
                        new
                        {
                            LoteID = 2,
                            CantidadActual = 50,
                            FechaEntrada = new DateTime(2025, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaVencimiento = new DateTime(2027, 5, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NumeroLote = "LOTE-A200",
                            ProductoID = 1
                        },
                        new
                        {
                            LoteID = 3,
                            CantidadActual = 75,
                            FechaEntrada = new DateTime(2025, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaVencimiento = new DateTime(2026, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NumeroLote = "LOTE-B500",
                            ProductoID = 2
                        });
                });

            modelBuilder.Entity("Farmacia_Paolo.Models.MovimientoInventario", b =>
                {
                    b.Property<int>("MovimientoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cantidad")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaMovimiento")
                        .HasColumnType("TEXT");

                    b.Property<int>("LoteID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoMovimiento")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("UsuarioID")
                        .HasColumnType("INTEGER");

                    b.HasKey("MovimientoID");

                    b.HasIndex("LoteID");

                    b.HasIndex("UsuarioID");

                    b.ToTable("MovimientosInventario");
                });

            modelBuilder.Entity("Farmacia_Paolo.Models.Producto", b =>
                {
                    b.Property<int>("ProductoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("ProveedorID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StockMinimo")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProductoID");

                    b.HasIndex("ProveedorID");

                    b.ToTable("Productos");

                    b.HasData(
                        new
                        {
                            ProductoID = 1,
                            Categoria = "Analgésico",
                            Codigo = "PROD-001",
                            Nombre = "Acetaminofén 500mg (Caja x20)",
                            Precio = 150.00m,
                            ProveedorID = 1,
                            StockMinimo = 20
                        },
                        new
                        {
                            ProductoID = 2,
                            Categoria = "Antibiótico",
                            Codigo = "PROD-002",
                            Nombre = "Amoxicilina 250mg (Suspensión)",
                            Precio = 450.00m,
                            ProveedorID = 2,
                            StockMinimo = 10
                        },
                        new
                        {
                            ProductoID = 3,
                            Categoria = "Vitaminas",
                            Codigo = "PROD-003",
                            Nombre = "Vitamina C 1000mg (Tubo x10)",
                            Precio = 700.00m,
                            ProveedorID = 1,
                            StockMinimo = 15
                        });
                });

            modelBuilder.Entity("Farmacia_Paolo.Models.Proveedor", b =>
                {
                    b.Property<int>("ProveedorID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("NombreProveedor")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("RNC")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("ProveedorID");

                    b.ToTable("Proveedores");

                    b.HasData(
                        new
                        {
                            ProveedorID = 1,
                            NombreProveedor = "Laboratorios MK",
                            RNC = "101001001",
                            Telefono = "809-555-1111"
                        },
                        new
                        {
                            ProveedorID = 2,
                            NombreProveedor = "Farmax",
                            RNC = "102002002",
                            Telefono = "809-555-2222"
                        });
                });

            modelBuilder.Entity("Farmacia_Paolo.Models.Rol", b =>
                {
                    b.Property<int>("RolID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("NombreRol")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("RolID");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RolID = 1,
                            NombreRol = "Administrador"
                        },
                        new
                        {
                            RolID = 2,
                            NombreRol = "Vendedor"
                        });
                });

            modelBuilder.Entity("Farmacia_Paolo.Models.Usuario", b =>
                {
                    b.Property<int>("UsuarioID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RolID")
                        .HasColumnType("INTEGER");

                    b.HasKey("UsuarioID");

                    b.HasIndex("RolID");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            UsuarioID = 1,
                            NombreCompleto = "Admin del Sistema",
                            NombreUsuario = "admin",
                            PasswordHash = "admin123",
                            RolID = 1
                        },
                        new
                        {
                            UsuarioID = 2,
                            NombreCompleto = "Juan Perez",
                            NombreUsuario = "vendedor1",
                            PasswordHash = "vendedor123",
                            RolID = 2
                        });
                });

            modelBuilder.Entity("Farmacia_Paolo.Models.Lote", b =>
                {
                    b.HasOne("Farmacia_Paolo.Models.Producto", "Producto")
                        .WithMany("Lotes")
                        .HasForeignKey("ProductoID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("Farmacia_Paolo.Models.MovimientoInventario", b =>
                {
                    b.HasOne("Farmacia_Paolo.Models.Lote", "Lote")
                        .WithMany("Movimientos")
                        .HasForeignKey("LoteID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Farmacia_Paolo.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lote");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Farmacia_Paolo.Models.Producto", b =>
                {
                    b.HasOne("Farmacia_Paolo.Models.Proveedor", "Proveedor")
                        .WithMany("Productos")
                        .HasForeignKey("ProveedorID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Proveedor");
                });

            modelBuilder.Entity("Farmacia_Paolo.Models.Usuario", b =>
                {
                    b.HasOne("Farmacia_Paolo.Models.Rol", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("RolID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("Farmacia_Paolo.Models.Lote", b =>
                {
                    b.Navigation("Movimientos");
                });

            modelBuilder.Entity("Farmacia_Paolo.Models.Producto", b =>
                {
                    b.Navigation("Lotes");
                });

            modelBuilder.Entity("Farmacia_Paolo.Models.Proveedor", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("Farmacia_Paolo.Models.Rol", b =>
                {
                    b.Navigation("Usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
